  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: YOUR_GOOGLE_CLIENT_ID
              client-secret: YOUR_GOOGLE_CLIENT_SECRET
              scope: profile, email
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              authorization-grant-type: authorization_code
              client-name: Google